# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowMain_.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(901, 410)
        MainWindow.setMinimumSize(QtCore.QSize(901, 410))
        MainWindow.setMaximumSize(QtCore.QSize(901, 410))
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(14, 20, 40);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.button_folder_images = QtWidgets.QPushButton(self.centralwidget)
        self.button_folder_images.setGeometry(QtCore.QRect(760, 120, 101, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.button_folder_images.setFont(font)
        self.button_folder_images.setStyleSheet("QPushButton{    \n"
"    border:2.5px solid;\n"
"    border-color: rgb(255,255,255);\n"
"    border-radius:5px;\n"
"    background-color: #A588D8;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(200,220,255);\n"
"}")
        self.button_folder_images.setObjectName("button_folder_images")
        self.input_folder_images = QtWidgets.QLineEdit(self.centralwidget)
        self.input_folder_images.setGeometry(QtCore.QRect(220, 120, 511, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.input_folder_images.setFont(font)
        self.input_folder_images.setStyleSheet("border:3px solid;\n"
"border-color: rgb(255,255,255);\n"
"border-radius:10px;\n"
"color:white;\n"
"padding-left: 10px;\n"
"")
        self.input_folder_images.setObjectName("input_folder_images")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 911, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.button_file_summary = QtWidgets.QPushButton(self.centralwidget)
        self.button_file_summary.setGeometry(QtCore.QRect(760, 190, 101, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.button_file_summary.setFont(font)
        self.button_file_summary.setStyleSheet("QPushButton{    \n"
"    border:2.5px solid;\n"
"    border-color: rgb(255,255,255);\n"
"    border-radius:5px;\n"
"    background-color: #A588D8;\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(200,220,255);\n"
"}")
        self.button_file_summary.setObjectName("button_file_summary")
        self.input_file_summary = QtWidgets.QLineEdit(self.centralwidget)
        self.input_file_summary.setGeometry(QtCore.QRect(220, 190, 511, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.input_file_summary.setFont(font)
        self.input_file_summary.setStyleSheet("border:3px solid;\n"
"border-color: rgb(255,255,255);\n"
"border-radius:10px;\n"
"color:white;\n"
"padding-left: 10px;\n"
"")
        self.input_file_summary.setObjectName("input_file_summary")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("color:white;")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.comboBox_lang = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_lang.setGeometry(QtCore.QRect(220, 260, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.comboBox_lang.setFont(font)
        self.comboBox_lang.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.comboBox_lang.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_lang.setAutoFillBackground(False)
        self.comboBox_lang.setStyleSheet("border:3px solid;\n"
"border-color: rgb(255,255,255);\n"
"border-radius:10px;\n"
"color:white;\n"
"padding-left: 10px;\n"
"")
        self.comboBox_lang.setMaxCount(10)
        self.comboBox_lang.setIconSize(QtCore.QSize(12, 12))
        self.comboBox_lang.setObjectName("comboBox_lang")
        self.comboBox_lang.addItem("")
        self.comboBox_lang.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("color:white;")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 330, 901, 62))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_extract = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_extract.sizePolicy().hasHeightForWidth())
        self.button_extract.setSizePolicy(sizePolicy)
        self.button_extract.setMinimumSize(QtCore.QSize(150, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.button_extract.setFont(font)
        self.button_extract.setStyleSheet("QPushButton{    \n"
"    border:2.5px solid;\n"
"    border-color:rgb(255,255,255);\n"
"    border-radius:10px;\n"
"    background-color: rgb(112,171,71);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(50,240,50);\n"
"}\n"
"")
        self.button_extract.setObjectName("button_extract")
        self.horizontalLayout.addWidget(self.button_extract)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.button_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.button_cancel.setMinimumSize(QtCore.QSize(150, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.button_cancel.setFont(font)
        self.button_cancel.setStyleSheet("QPushButton{    \n"
"    border:2.5px solid;\n"
"    border-color: rgb(255,255,255);\n"
"    border-radius:10px;\n"
"    background-color: rgb(246,180,153);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(246,50,50);\n"
"}")
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.button_reset = QtWidgets.QPushButton(self.centralwidget)
        self.button_reset.setGeometry(QtCore.QRect(760, 260, 101, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_reset.sizePolicy().hasHeightForWidth())
        self.button_reset.setSizePolicy(sizePolicy)
        self.button_reset.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.button_reset.setFont(font)
        self.button_reset.setStyleSheet("QPushButton{    \n"
"    border:2.5px solid;\n"
"    border-color:rgb(255,255,255);\n"
"    border-radius:10px;\n"
"    background-color: rgb(112,171,171);\n"
"    color: rgb(0,0,0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(50,240,50);\n"
"}\n"
"")
        self.button_reset.setObjectName("button_reset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Convert from image & Summarize Consult Data  - ver2.0"))
        self.label_3.setText(_translate("MainWindow", "Folder Images:"))
        self.button_folder_images.setText(_translate("MainWindow", "Select"))
        self.label_2.setText(_translate("MainWindow", "Convert from image & Summarize Consult Data"))
        self.button_file_summary.setText(_translate("MainWindow", "Select"))
        self.label_5.setText(_translate("MainWindow", "File Summary:"))
        self.comboBox_lang.setItemText(0, _translate("MainWindow", "Japan"))
        self.comboBox_lang.setItemText(1, _translate("MainWindow", "English"))
        self.label_6.setText(_translate("MainWindow", "Language:"))
        self.button_extract.setText(_translate("MainWindow", "Run"))
        self.button_cancel.setText(_translate("MainWindow", "Cancel"))
        self.button_reset.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
